"""LaTeX tables for the report, plus the drift-only baseline for the S&P 500.

Writes to tables/:
    datasets.tex   the five series as used in the final runs, with stationarity
                   tests before and after the pre-processing transform
    tuning.tex     selected hyperparameters and the resulting number of weights
Prints the drift-only baseline comparison for the S&P 500.
"""
from __future__ import annotations

import numpy as np
import pandas as pd

import data
import pipeline as P
import run
import transforms
from common import ROOT, RESULTS_DIR
from models import MODELS, build_model

TABLE_DIR = ROOT / "tables"
TABLE_DIR.mkdir(exist_ok=True)

ORDER = ["mackey_glass", "electricity", "pageviews", "temperature", "sp500"]
NAME = {"mackey_glass": "Mackey-Glass", "electricity": "Electricity",
        "pageviews": "Page views", "temperature": "Temperature",
        "sp500": "S\\&P 500"}
FREQ = {"mackey_glass": "Time step", "electricity": "Hourly",
        "pageviews": "Daily", "temperature": "Daily", "sp500": "Trading day"}
M_NAME = {"elman": "Elman", "jordan": "Jordan", "mrnn": "Multi-recurrent"}
TRANSFORM_TEX = {"none": "None", "log1p": "$\\ln(1+x_t)$",
                 "logdiff": "$\\ln x_t - \\ln x_{t-1}$"}
# The ADF and KPSS tests disagree on electricity
VERDICT_TEX = {"difference-stationary": "Tests disagree"}
# WR23f: data archives belong in footnotes, not the bibliography.
SOURCES = {
    "mackey_glass": "generated by numerical integration",
    "electricity": "PJM Interconnection hourly load, PJME region",
    "pageviews": "Wikimedia pageviews API, article Masters_Tournament",
    "temperature": "Australian Bureau of Meteorology, Melbourne",
    "sp500": "Yahoo Finance, ticker ^GSPC",
}

def fmt_p(p: float, kind: str) -> str:
    """KPSS p-values are interpolated from a table and clipped to [0.01, 0.10]."""
    if kind == "kpss" and p >= 0.1:
        return "$\\geq 0.10$"
    if kind == "kpss" and p <= 0.01:
        return "$\\leq 0.01$"
    return "$<0.001$" if p < 0.001 else f"{p:.3f}"


def datasets_table() -> pd.DataFrame:
    rows = []
    for ds in ORDER:
        try:
            raw = run.series_for(ds)                 # exactly what run.py used
        except Exception as e:                       # pragma: no cover
            print(f"  skipped {ds}: {e}")
            continue
        full = data.DATASETS[ds]()
        used = full.iloc[-len(raw):]                 # dates of the portion used
        before = data.describe(used)
        T = transforms.get(transforms.DATASET_TRANSFORM[ds])
        work = pd.Series(T.to_work(raw), name=ds)
        after = data.describe(work) if T.name != "none" else before
        rows.append(dict(
            dataset=ds, n=len(raw), freq=FREQ[ds],
            start=str(used.index[0])[:10] if ds != "mackey_glass" else "",
            end=str(used.index[-1])[:10] if ds != "mackey_glass" else "",
            adf_p=before["adf_p"], kpss_p=before["kpss_p"], verdict=before["verdict"],
            transform=T.name, verdict_after=after["verdict"],
            adf_p_after=after["adf_p"], kpss_p_after=after["kpss_p"]))
    df = pd.DataFrame(rows)
    df.to_csv(RESULTS_DIR / "datasets_table.csv", index=False)

    lines = []
    for _, r in df.iterrows():
        lines.append(" & ".join([
            NAME[r["dataset"]], f"{r['n']:,}".replace(",", "\\,"), r["freq"],
            fmt_p(r["adf_p"], "adf"), fmt_p(r["kpss_p"], "kpss"),
            VERDICT_TEX.get(r["verdict"], r["verdict"]),
            TRANSFORM_TEX[r["transform"]],
            VERDICT_TEX.get(r["verdict_after"], r["verdict_after"])]) + " \\\\")
    tex = ("\\begin{table*}[t]\n\\centering\n"
           "\\caption{Characteristics of the Five Time Series}\n"
           "\\label{tab:datasets}\n"
           "\\begin{tabular}{@{}lrlcclll@{}}\n\\toprule\n"
           "Series & Length & Frequency & ADF $p$ & KPSS $p$ & Verdict & "
           "Transform & Verdict after transform \\\\\n\\midrule\n"
           + "\n".join(lines) + "\n\\bottomrule\n\\end{tabular}\n\\end{table*}\n")
    (TABLE_DIR / "datasets.tex").write_text(tex)
    return df


def n_weights(model: str, hidden: int) -> int:
    return sum(p.numel() for p in build_model(model, hidden).parameters())


def tuning_table() -> pd.DataFrame:
    best = run.merge_tuning()
    rows = []
    for ds in ORDER:
        for m in MODELS:
            r = best[(best.dataset == ds) & (best.model == m)]
            if r.empty:
                continue
            r = r.iloc[0]
            rows.append(dict(dataset=ds, model=m, window=int(r["window"]),
                             hidden=int(r.n_hidden), lr=float(r["lr"]),
                             weight_decay=float(r["weight_decay"]),
                             weights=n_weights(m, int(r.n_hidden)),
                             u_dev=float(r.theil_u_dev)))
    df = pd.DataFrame(rows)
    df.to_csv(RESULTS_DIR / "tuning_table.csv", index=False)

    def sci(x):
        if x == 0:
            return "0"
        e = int(np.floor(np.log10(x)))
        return f"$10^{{{e}}}$" if np.isclose(x, 10.0 ** e) else f"{x:.1e}"

    lines = []
    for ds in ORDER:
        g = df[df.dataset == ds]
        for i, (_, r) in enumerate(g.iterrows()):
            lead = NAME[ds] if i == 0 else ""
            lines.append(" & ".join([
                lead, M_NAME[r["model"]], str(r["window"]), str(r["hidden"]),
                f"{r['lr']:.4f}", sci(r["weight_decay"]), str(r["weights"])]) + " \\\\")
        lines.append("\\midrule")
    lines = lines[:-1]
    tex = ("\\begin{table}[t]\n\\centering\n"
           "\\caption{Selected Hyperparameters and Number of Weights}\n"
           "\\label{tab:tuning}\n\\footnotesize\n"
           "\\setlength{\\tabcolsep}{4pt}\n"
           "\\begin{tabular}{@{}llrrrrr@{}}\n\\toprule\n"
           "Series & Network & $d$ & $J$ & $\\eta$ & $\\lambda$ & Weights \\\\\n"
           "\\midrule\n" + "\n".join(lines) +
           "\n\\bottomrule\n\\end{tabular}\n\\end{table}\n")
    (TABLE_DIR / "tuning.tex").write_text(tex)
    return df


def drift_baseline() -> pd.DataFrame:
    """Theil U of 'persistence plus mean training return' on the S&P 500 folds.

    A network whose output stays near zero in standardised space forecasts the
    training mean of the inputs once the standardisation is undone. With the
    log-return transform that mean is the historical drift, so the forecast is
    the last price multiplied by exp(drift). This function computes exactly
    that forecast on each model's own held-out folds.
    """
    try:
        raw = run.series_for("sp500")
        runs = pd.read_csv(RESULTS_DIR / "final_runs_sp500.csv")
    except Exception as e:
        print(f"  drift baseline skipped: {e}")
        return pd.DataFrame()

    best = run.merge_tuning()
    rows = []
    for m in MODELS:
        cfg = run.final_config("sp500", m, best)
        T = transforms.get(cfg.transform)
        work = T.to_work(raw)
        X, _ = P.make_windows(work, cfg.window, cfg.horizon)
        splits = P.cv_splits(P.n_windows(raw, cfg), cfg, run.HOLDOUT_START)
        for fold, (tr, te) in enumerate(splits):
            drift = float(X[tr].mean())               # same mean the scaler uses
            tgt = P.target_index(te, cfg)
            anchor = T.anchors(raw, tgt, cfg.horizon)
            y = T.true_values(raw, tgt)
            u_drift = (np.sqrt(np.mean((anchor * np.exp(drift) - y) ** 2))
                       / np.sqrt(np.mean((anchor - y) ** 2)))
            u_model = runs[(runs.model == m) & (runs.fold == fold)].theil_u.mean()
            rows.append(dict(model=m, fold=fold, drift_per_day=drift,
                             u_drift=u_drift, u_model=u_model))
    df = pd.DataFrame(rows)
    df.to_csv(RESULTS_DIR / "sp500_drift_baseline.csv", index=False)
    return df


if __name__ == "__main__":
    print("Datasets (as used in the final runs):")
    d = datasets_table()
    print(d[["dataset", "n", "start", "end", "adf_p", "kpss_p", "verdict",
             "transform", "verdict_after"]].to_string(index=False), "\n")
    print("Footnote sources (WR23f):")
    for ds in ORDER:
        print(f"  {ds:13s} {SOURCES[ds]}")
    print()

    print("Selected hyperparameters:")
    print(tuning_table().to_string(index=False), "\n")

    db = drift_baseline()
    if not db.empty:
        print("S&P 500: network versus drift-only baseline, per held-out fold")
        print(db.round(5).to_string(index=False), "\n")
        s = db.groupby("model")[["u_model", "u_drift"]].mean()
        s["gap"] = s.u_model - s.u_drift
        print("Mean over folds (gap near zero means the network is the drift forecast):")
        print(s.round(5).to_string(), "\n")
        print(f"Correlation of fold-level U, network vs drift: "
              f"{np.corrcoef(db.u_model, db.u_drift)[0, 1]:.3f}")

    print(f"\nTables written to {TABLE_DIR}")